repos:
  - repo: local
    hooks:
      - id: compile-ui
        name: Compile Qt .ui files before commit
        entry: poetry run compile-ui
        language: system
        types: [python]
        files: \.ui$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8 # Use the latest stable version
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --line-length=120]
        # Run the formatter.
      - id: ruff-format
        args: [--line-length=120]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
