"""View class for the DCMspec Explorer application."""

from PySide6.QtCore import Signal
from PySide6.QtWidgets import QMainWindow
from dcmspec_explorer.view.main_window_ui import Ui_MainWindow  # Generated by: pyside6-uic from main_window.ui


class MainWindow(QMainWindow):
    """Provide the main application window for the DCMspec Explorer.

    Set up and display the primary user interface for browsing and exploring DICOM specifications.
    """

    # Define a custom signal that will be emitted when the window is shown.
    window_shown = Signal()

    def __init__(self):
        """Initialize the main window using compiled UI from Qt Designer.

        Load the UI helper class generated by pyside6-uic from the .ui file and set up the main window.
        """
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        # Access widgets as self.ui.myButton, etc.

    def showEvent(self, event):
        """Override the Qt showEvent to emit a custom signal after the window is shown.

        Allows to add custom behavior that should happen right after the window is displayed to the user.
        """
        # Call the base class implementation to ensure the window is displayed correctly.
        super().showEvent(event)
        # Emit the custom signal to notify that the window has been shown.
        self.window_shown.emit()

    def update_status_bar(self, message):
        """Update the status bar with a message."""
        self.statusBar().showMessage(message)

    def update_treeview(self, tree_model):
        """Update the treeview with a new model."""
        self.ui.iodTreeView.setModel(tree_model)
        # Set default column widths
        self.ui.iodTreeView.setColumnWidth(0, 400)  # Name
        self.ui.iodTreeView.setColumnWidth(1, 100)  # Kind
        self.ui.iodTreeView.setColumnWidth(2, 30)  # Usage
        self.ui.iodTreeView.setColumnWidth(3, 20)  # Favorite

    def show_error(self, message):
        """Show an error message dialog."""
        from PySide6.QtWidgets import QMessageBox

        QMessageBox.critical(self, "Error", message)
